export const REGIONS = [
  "Andalucia",
  "Aragon",
  "Asturias",
  "Islas Baleares",
  "Canarias",
  "Cantabria",
  "Castilla-La Mancha",
  "Castilla y Leon",
  "Cataluna",
  "Comunidad Valenciana",
  "Extremadura",
  "Galicia",
  "Comunidad de Madrid",
  "Murcia",
  "Navarra",
  "Pais Vasco",
  "La Rioja",
  "Ceuta",
  "Melilla",
] as const;
